# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LAKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LAKit
  pod 'LCNavgation', '~> 0.0.2'
  pod 'AFNetworking', '~> 3.2.1'

end
